# Generated by Django 5.0.6 on 2024-07-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField()),
                ('groupId', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('countryCode', models.CharField(max_length=16)),
            ],
        ),
    ]
