# Generated by Django 5.0.6 on 2024-07-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiBackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('countryCode', models.CharField(max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='country',
            name='countryCode',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name',
        ),
    ]
