# Generated by Django 5.0.6 on 2024-07-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiBackend', '0002_countrycreate_remove_country_countrycode_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountryCreate',
        ),
        migrations.AddField(
            model_name='country',
            name='countryCode',
            field=models.CharField(default='A', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='name',
            field=models.CharField(default='B', max_length=64),
            preserve_default=False,
        ),
    ]
